### PR TITLE
[WIP] netCDF parser

### PR DESCRIPTION
**Pull request by katieannemills**
In this PR we'll develop a parser to ingest netCDF-formatted profile data. Requirements:

 - Should produce profile objects that are non-breaking for code written to ingest profile objects from wod.py (most notably the AutoQC suite).
 - Should support IQuOD and WOD flags at a minimum (others?)

This is ongoing work - comments and requests welcome, please post below.

### CODE REVIEW

**Comment by katieannemills** [comment]
Still very early days, but 2a688e4 begins to lay out the structure and hit the low-hanging fruit. Still need unit tests and guardrails for graceful failure, but a few things immediately jump out:

 - a few things (probe type; lat/long uncertainty; pressure; some others) don't obviously appear in the netCDF file I grabbed from wodSelect. @BoyerWOD are these present in some but not all such files, or are they not currently supported in netCDF profiles?
 - I want the class methods and signatures to be a superset of those found in wod.py so we don't break anything downstream; there are some though that probably don't make sense in netCDF (primary / secondary headers jump to mind) - dummy methods are there now, but we may rethink this after the more important issues above are handled.

**Comment by durack1** [comment]
@BillMills I am just pinging myself on this thread. I am keen to be in the loop as new profile standards/conventions are being discussed, it would be great if such a format could be standardized (similar to the CMIP data conventions), so we have full provenance for the data source and its processing.

As an FYI, for the CMIP metadata spec, you can peruse this at https://goo.gl/v1drZl (CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s)

**Comment by BoyerWOD** [comment]
Bill,
"a few things (probe type; lat/long uncertainty; pressure; some others) don't obviously appear in the netCDF file I grabbed from wodSelect. @BoyerWOD are these present in some but not all such files, or are they not currently supported in netCDF profiles?"

Those variables exist, but if no individual casts in a file have values for a given variable, the variable is not included in that particular file.  For instance, lat/lon uncertainty is an agreed upon variable needed for IQuOD, but as of now, this uncertainty is not defined for any particular measurement method (from dead reckoning to GPS). so the variable does not yet appear in any IQuOD file.  pressure will not appear unless pressure is measured, so an XBT file, for instance will not have a pressure variable."

"I want the class methods and signatures to be a superset of those found in wod.py so we don't break anything downstream; there are some though that probably don't make sense in netCDF (primary / secondary headers jump to mind) - dummy methods are there now, but we may rethink this after the more important issues above are handled."

No strong feelings here, but primary and secondary header still have sense in that a primary header is universally necessary to utilize a cast, whereas secondary headers are auxiliary information (though in some cases important for utilizing cast, such as XBT depth equation).

Paul, the IQuOD files follow the Climate-Forecast (CF) convention.  I dont have any initial objection to following CMIPs set of global attributes, we can talk about this at the IQuOD meeting in a little over a week.  This discussion may be better pursued under the format thread.

**Comment by katieannemills** [comment]
Thanks for your comments, @BoyerWOD - one other thing: currently the silicate, phosphate and oxygen content tests are failing when I use wodselect to find a netCDF version of the example profile parsed in an appendix of the ASCII document (the same one we base wodpy's unit testing on), and compare it to the values reported in that document. In the case of silicate and phosphate, the numbers are close but not an exact match, and in the case of oxygen it appears to be reported in umol/kg in the netCDF file, but ppm in the ascii. Does all that sound unsurprising, or does that sound suspicious to you?

After that, next steps will be to get ahold of an example profile(s) with everything included (pressure, metadata etc) to build those methods out, and then we can make a release.

Also re:
> primary header is universally necessary to utilize a cast

this is true in the sense that you need the _data_ from the header (lat, long, timestamp etc), not the literal header itself I assume. If that's not correct and a specific header object is actually expected, let me know.

**Comment by durack1** [comment]
> Paul, the IQuOD files follow the Climate-Forecast (CF) convention. I dont have any initial objection to following CMIPs set of global attributes, we can talk about this at the IQuOD meeting in a little over a week. This discussion may be better pursued under the format thread.

No problem @BoyerWOD, the CMIP6 global attributes are an expansion on CF and these are very model specific, but does provide some food for thought with regard to additional metadata that better defines the data in a netcdf file, for reference the CMIP6 metadata specs are defined in the [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV's](http://goo.gl/v1drZl) document

**Comment by katieannemills** [comment]
Today's commits get in line with the current draft of the IQuOD spec; more work to be done on both documents still, but this makes overall direction much clearer.

**Comment by castelao** [comment]
Hi @BillMills , how can I help? What is missing?

**Comment by katieannemills** [comment]
Hi @castelao, thanks for reviving interest here - as noted I'd like to get this finally done asap. This evening I did some cleanup to clarify the remaining work and get the existing tests passing; see in `wodpy/wodnc.py` there are a bunch of helper functions that are just stubs that do nothing but `return None`. There are a few classes here:

 - [definitely easy] the measurements like oxygen, phosphate etc: I was concerned that the netCDF file I found that matched the example profile we were testing against didn't seem to _exactly_ match what was reported in the ASCII version of the profile; this is weird, but we don't need to be blocked by it, we can just test and validate against whatever is in the netCDF file. I'll take care of this shortly.
 - [maybe easier in 2022 than it was in 2019]: as Tim noted above, we didn't at the time have any examples of netCDF files that had some variables like lat/lon uncertainty and IQuOD metadata objects. Perhaps these exist now? I think this PR hung up 3 years ago when that data didn't seem available yet.

Once those are  in hand so we can build tested functions, we can add the trivial dataframe helpers, and finally make sure your cotede adapter ingests netCDF-derived profile class objects, and we'll be done. I'll look around for appropriate testing examples over the next couple of days and let you know if I'm really stuck, hopefully they're readily available now.

**Comment by castelao** [comment]
What about `raise NotImplemented` instead of `return None` and release as it is? It is already a great achievement to be able to read T & S. With time, we can work one by one on the missing functions.

I also send some suggestions in a PR directly to your branch. Feel free to close that if there is nothing useful there.

**Comment by castelao** [comment]
@BillMills , thanks for your time advancing this. It will be very useful. I do appreciate it.

**Comment by katieannemills** [comment]
@castelao per your encouragement, `wodpy 2.0.0b0`is now available on PyPI. For the absolute minimal experience, `pip install wodpy==2.0.0b0`, and then something like:

```
from wodpy import wodnc

r = wodnc.Ragged('ocldb1570984477.6279_OSD.nc')
p = wodnc.ncProfile(r, 55)
```

And `p` will have (most of) the profile API you know and love from the ASCII wodpy implementation, representing the 55th profile from the WOD file noted. As noted in the release notes, I'm calling this a beta since we need to add some clarity around exactly what netCDF format we're promising to parse, and then build tests around an example of that. Just as the ASCII parser points to a spec document and tests against an example of it, I want to see a clearer parallel with a WOD / IQuOD compliant netCDF example before we come out of beta - but hopefully this gets us unstuck and moving until then. Of course, any problems, requests or suggestions are very welcome and the beta period is the ideal time to address them. Thanks for motivating the project forward!

**Comment by castelao** [comment]
@BillMills , thanks!!! Later this week, maybe on the weekend, I'll try to use it to update the ExpertQC dataset. I'll let you know how it works.

**Pull request merged**
