### PR TITLE
Adding datetime procedure, and minor bug fix

### PR DESCRIPTION
**Pull request by castelao**
There was a minor bug on the code copied from AutoQC to extract the seconds. Also, the date time procedure might be useful outside Wod4CoTeDe, so I suggest to move it into the main core.

### CODE REVIEW

**Comment by katieannemills** [comment]
Great, thanks for this! As discussed [here](https://github.com/IQuOD/AutoQC/pull/134#issuecomment-169535024), I'm a bit concerned about setting the day to 15 when it's 0 in the profile; if data isn't there or is nonsense, we should return `none`, rather than guess and create a potentially harmful bias. @castelao, how do you feel about this? @s-good, feel free to weigh in too.

**Comment by s-good** [comment]
Hi, yes I think I agree that it is best not to assume a day or time if it is not available. Do you think it best to return None or to have an exception raised?

**Comment by castelao** [comment]
I agree, None is probably better. In concept there is no failure reading the data, just the date/time is not available, hence none. For the QC perspective, other tests could be applied even without date, and a fail on valid datetime is usually flag 3.

**Comment by katieannemills** [comment]
+1 to @castelao's explanation - no need to stop the show just because the day is unavailable; that's a decision we can punt to the analysis step.

**Pull request merged**
