### PR TITLE
IQuOD 0.1 parsing

### PR DESCRIPTION
**Pull request by katieannemills**
cc @s-good @BecCowley @boyerWOD

Hi team - here's a first pass at an IQuOD ascii 0.1 parser. I approached this by making wodpy able to transparently ingest both the WOD13 and IQuOD 0.1 ascii formats, and return compatible objects. New methods of note:

 - `dlatitude()`: uncertainty on latitude; `None` if uncertainty is missing (either because it's missing in the IQuOD 0.1 data, or because this was a WOD13 format file.
 - `dlongitude`, `dz`, `dt` and `ds`: analogous to the above for longitude, depth, temperature and salinity. Note if a variable is missing at a given level, we assume the uncertainty for that level is also missing.
 - `t_metadata()` and `s_metadata()`: returns lists of dictionaries containing metadata for temperature and salinity respectively, with keys `code` (table 5 from https://data.nodc.noaa.gov/woa/WOD/DOC/wodreadme.pdf); `value` (the actual value for the subsidiary metadata flag); and `intMeta` (0 or 1 indicating whether this is intelligent metadata or not).
 - underlying functions `dvar_data` and `var_metadata` to unpack generic uncertainties and metadata (besides temperature and salinity), in analogy with how wodpy handles general variables.

Note the metadata dictionaries are entirely new, not just the intelligent metadata flag.  

Let me know any thoughts or comments on this - even better, try it out on some oddball profiles and let me know any problems that come up; if it looks good we can stamp a new release. I'm thinking of copying over dicts for decoding the metadata encodings, but that'll take a while and is a relatively superficial change.

### CODE REVIEW

**Comment by s-good** [comment]
Thanks for doing this! 

Just a few comments on the names. It might be just me, but putting 'd' in front of names makes me think of a difference rather an uncertainty. We could put _unc or _uncertainty on the ends of names instead e.g. latitude_unc. I wonder if the 'int' in intMeta might get confused with integer, also. At the meeting, people seemed to be using iMeta. Others might have different opinions, though, so I would be interested in what other people think.

**Comment by BecCowley** [comment]
Thanks @BillMills. I will have a go at using it in the next few weeks. I agree with @s-good - please can we change the 'd' part. We often  use dt, dz to indicate a gradient or difference. Could be confusing.
Will let you know how I go.

**Comment by katieannemills** [comment]
Thanks for the comments @BecCowley and @s-good; since last time:

 - `d*` syntax changed to `*_unc` per your request
 - `intMeta` -> `iMeta` per your request
 - pandas column names and metadata names matched to function names and ndarray keys (so the same name extracts the same data in all cases, rather than for example `z` in the ndarray and but `depth` in the dataframe).
 - All profile-level information assigned as attributes to the dataframe are now keys in a dictionary `meta` assigned to the dataframe (that way all the metadata can be migrated at once easily)

I'm going to stamp this as `2.0` at the end of the month, unless there are any other requests first. Thanks as always for your feedback!

**Comment by katieannemills** [comment]
OK, wodpy v 1.6.0 has been released as  <a href="https://zenodo.org/badge/latestdoi/39165450">DOI</a>; let me know any comments as always.

(I decided to save the 2.0.0 bump for when we expand to netCDF support, which is one of my medium-term projects, second to getting AutoQC's first data release out).

**Pull request merged**
